name: Flutter check
on:
  push:
    branches:
      - main
  pull_request:
      types:
      - opened
      - reopened
      branches:
      - main
jobs:
  check-flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.x
      - run: java --version
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk